"""Loader for the legal playbook -- a taxonomy of clause categories, each
with a handful of verbatim example clauses pulled from real contracts.

Built from four sources, each generated by its own scripts/build_*.py
against a dataset under data/ (see each script's docstring for details):
  - CUAD v1        (cuad_playbook.json)        -- 41 categories, 510 contracts
  - LEDGAR         (ledgar_playbook.json)       -- 100 categories, 80k clauses
  - Unfair ToS     (unfair_tos_playbook.json)   -- 8 categories, 9.4k sentences
  - ContractNLI    (contractnli_playbook.json)  -- 17 NDA risk hypotheses

This is purely a browsable reference set (Playbook page "reference
categories" panel, and example language for Phase 6 redline fallback
suggestions). It is intentionally NOT wired into the live topic-alignment
config (app/playbook/topic_rules.py) that drives Phase 5 contradiction
detection -- that stays a small, user-edited list so adding reference
categories here never silently changes analysis cost or behavior.

Category names can collide across sources (e.g. CUAD's "Governing Law" vs
LEDGAR's "Governing Laws" are distinct strings and both kept), so every
category is tagged with its `source` and callers needing a single category
should filter by (source, category) together, not category name alone.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_PLAYBOOK_DIR = Path(__file__).resolve().parent
_PLAYBOOK_FILES = [
    "cuad_playbook.json",
    "ledgar_playbook.json",
    "unfair_tos_playbook.json",
    "contractnli_playbook.json",
]


@lru_cache(maxsize=1)
def load_playbooks() -> list[dict]:
    """Loads every playbook JSON that has actually been generated. Missing
    files are skipped (not an error) so the app still runs if only some of
    the optional datasets have been downloaded and built."""
    playbooks = []
    for filename in _PLAYBOOK_FILES:
        path = _PLAYBOOK_DIR / filename
        if path.exists():
            playbooks.append(json.loads(path.read_text(encoding="utf-8")))
    if not playbooks:
        raise FileNotFoundError(
            f"No playbook files found in {_PLAYBOOK_DIR}. Run the scripts/build_*_playbook.py "
            "scripts (each requires its corresponding dataset under data/)."
        )
    return playbooks


def list_categories() -> list[dict]:
    """Returns every (source, category) pair across all loaded playbooks."""
    return [
        {"source": playbook["source"], "category": c["category"]}
        for playbook in load_playbooks()
        for c in playbook["categories"]
    ]


def get_category(source: str, name: str) -> dict | None:
    for playbook in load_playbooks():
        if playbook["source"] != source:
            continue
        for c in playbook["categories"]:
            if c["category"].lower() == name.lower():
                return {**c, "source": playbook["source"]}
    return None


def list_all_categories() -> list[dict]:
    """Every category from every source, each tagged with its source and
    truncated to its first couple of example clauses -- what the Playbook
    page's reference panel renders."""
    return [
        {**c, "source": playbook["source"]}
        for playbook in load_playbooks()
        for c in playbook["categories"]
    ]
