"""Verifies the PDF report actually contains what was sent in, by re-parsing
the generated bytes with PyMuPDF (already a dependency for Phase 2 parsing)
rather than just asserting "some bytes came out"."""
import fitz
import pytest

from app.models.audit import AuditEntry
from app.models.obligation import Obligation
from app.models.report import ReportRequest, ReportRiskFlag
from app.services.report_service import generate_report_pdf


def _extract_text(pdf_bytes: bytes) -> str:
    with fitz.open(stream=pdf_bytes, filetype="pdf") as doc:
        return "\n".join(page.get_text() for page in doc)


def _risk_flag(**overrides) -> ReportRiskFlag:
    defaults = dict(id="flag-1", kind="contradiction", severity="high", title="Payment Terms conflict", description="45 vs 15 days")
    defaults.update(overrides)
    return ReportRiskFlag(**defaults)


def _obligation(**overrides) -> Obligation:
    defaults = dict(
        id="obl-1", doc_id="sow-1", clause_id="sow-1::3.3", section_number="3.3", heading="Invoice Terms",
        text="Client shall pay invoices within fifteen days of receipt.", responsible_party="Client",
        obligation_verb="shall", deadline_text="within fifteen days", deadline_days=15, page=2,
    )
    defaults.update(overrides)
    return Obligation(**defaults)


def _audit_entry(**overrides) -> AuditEntry:
    defaults = dict(
        id="audit-1", msa_doc_id="msa-1", sow_doc_id="sow-1", doc_id="sow-1", clause_id="sow-1::3.3",
        topic="Payment Terms", original_text="Client shall pay invoices within fifteen days of receipt.",
        risk_rating="contradiction", decision="approved", reviewer="J. Smith", created_at="2026-07-14T10:00:00Z",
        decided_at="2026-07-14T11:00:00Z",
    )
    defaults.update(overrides)
    return AuditEntry(**defaults)


def test_report_contains_document_names_and_generated_timestamp():
    request = ReportRequest(msa_filename="msa_sample.pdf", sow_filename="sow_sample.pdf")
    text = _extract_text(generate_report_pdf(request))
    assert "msa_sample.pdf" in text
    assert "sow_sample.pdf" in text
    assert "Generated" in text
    assert "UTC" in text


def test_report_with_no_findings_shows_empty_states():
    request = ReportRequest(msa_filename="msa.pdf", sow_filename="sow.pdf")
    text = _extract_text(generate_report_pdf(request))
    assert "No risks flagged for this document pair." in text
    assert "No obligations detected in these documents." in text
    assert "No audit trail entries recorded for this document pair." in text


def test_report_includes_risk_flag_details():
    request = ReportRequest(msa_filename="msa.pdf", sow_filename="sow.pdf", risk_flags=[_risk_flag()])
    text = _extract_text(generate_report_pdf(request))
    assert "Payment Terms conflict" in text
    assert "45 vs 15 days" in text
    assert "HIGH" in text


def test_report_severity_counts_are_correct():
    flags = [_risk_flag(id="f1", severity="high"), _risk_flag(id="f2", severity="medium"), _risk_flag(id="f3", severity="low")]
    request = ReportRequest(msa_filename="msa.pdf", sow_filename="sow.pdf", risk_flags=flags)
    text = _extract_text(generate_report_pdf(request))
    assert "1 high" in text
    assert "1 medium" in text
    assert "1 low" in text


def test_contradiction_details_section_only_appears_for_flags_with_confidence():
    flags = [_risk_flag(id="f1", confidence=0.97), _risk_flag(id="f2", kind="circular_reference", severity="medium", confidence=None)]
    request = ReportRequest(msa_filename="msa.pdf", sow_filename="sow.pdf", risk_flags=flags)
    text = _extract_text(generate_report_pdf(request))
    assert "Contradiction Details" in text
    assert "97%" in text


def test_contradiction_details_section_omitted_when_no_confidence_scores():
    flags = [_risk_flag(kind="circular_reference", severity="medium", confidence=None)]
    request = ReportRequest(msa_filename="msa.pdf", sow_filename="sow.pdf", risk_flags=flags)
    text = _extract_text(generate_report_pdf(request))
    assert "Contradiction Details" not in text


def test_report_includes_obligation_details():
    request = ReportRequest(msa_filename="msa.pdf", sow_filename="sow.pdf", obligations=[_obligation()])
    text = _extract_text(generate_report_pdf(request))
    assert "Client" in text
    assert "3.3" in text
    assert "15d" in text
    assert "within fifteen days of receipt" in text


def test_report_includes_audit_trail_details():
    request = ReportRequest(msa_filename="msa.pdf", sow_filename="sow.pdf", audit_entries=[_audit_entry()])
    text = _extract_text(generate_report_pdf(request))
    assert "Payment Terms" in text
    assert "APPROVED" in text
    assert "J. Smith" in text


def test_report_includes_human_review_disclaimer():
    request = ReportRequest(msa_filename="msa.pdf", sow_filename="sow.pdf")
    text = _extract_text(generate_report_pdf(request))
    assert "human review" in text


def test_missing_deadline_and_reviewer_render_without_mojibake():
    """Regression guard: an em-dash ('—') placeholder for a missing
    deadline/reviewer/section rendered as a replacement-character glyph
    ('�') when extracted from the PDF, in both reportlab's Paragraph
    markup layer and canvas.drawString -- found by inspecting a real
    generated report. Fixed by using an ASCII '--' fallback instead,
    matching the convention already used throughout this codebase's source
    comments for the same reason."""
    obligation = _obligation(section_number=None, deadline_days=None)
    audit_entry = _audit_entry(reviewer=None)
    request = ReportRequest(msa_filename="msa.pdf", sow_filename="sow.pdf", obligations=[obligation], audit_entries=[audit_entry])
    text = _extract_text(generate_report_pdf(request))
    assert "�" not in text
    assert "—" not in text


def test_special_characters_in_clause_text_do_not_break_pdf_generation():
    """reportlab's Paragraph uses HTML-like markup -- unescaped '<', '>', '&'
    in AI-generated explanations or clause text must not crash rendering."""
    flag = _risk_flag(title="A & B <conflict>", description="Uses < and > and & characters")
    request = ReportRequest(msa_filename="msa.pdf", sow_filename="sow.pdf", risk_flags=[flag])
    text = _extract_text(generate_report_pdf(request))
    assert "A & B <conflict>" in text
